server:
  servlet:
    context-path: /api/v1
  port: ${PORT:8081}
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active:
      - ${ACTIVE_PROFILE:dev}
  main:
    banner-mode: OFF
  application:
    name: FinderUnited
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI}
      database: FinderUnited
jwt:
  secret-key: ${JWT_SECRET_KEY}

aws:
  s3:
    bucket: ${AWS_BUCKET_NAME}
  cloud:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
  region:
    static: ${AWS_REGION}
  stack:
    auto: false
